"""initial schema

Revision ID: ee6e6a0923fa
Revises: 
Create Date: 2026-09-02 17:40:43.457876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee6e6a0923fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('SCREENING', 'DESIGN_ASSESSMENT', 'COMMERCIAL_ASSESSMENT', name='checklist_stage'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage', 'version', name='uq_checklist_stage_version')
    )
    op.create_table('sequence_counters',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('terms_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('terms_type', sa.Enum('SUBMISSION_TERMS', 'SUPPLY_ENQUIRY_TERMS', name='terms_type'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terms_type', 'version', name='uq_terms_type_version')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DESIGN_REVIEWER', 'COMMERCIAL_REVIEWER', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('track', sa.Enum('DESIGNER', 'MANUFACTURER', 'BRAND', name='submission_track'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('terms_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['terms_version_id'], ['terms_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_reference_number'), 'submissions', ['reference_number'], unique=True)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('checklist_template_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('checked_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('all_checked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_template_id'], ['checklist_templates.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_shape_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('deal_shape', sa.Enum('CO_DEVELOPMENT', 'SELL_IP_ROYALTY', 'LICENSE', 'BUYOUT', name='deal_shape'), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('declined_ip_register',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submitter_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('declined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decline_reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_clocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('clock_type', sa.Enum('ACK_48H', 'SCREEN_10BD', 'EVAL_30BD', name='sla_clock_type'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'MET', 'BREACHED', 'CANCELLED', name='sla_clock_status'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'clock_type', name='uq_submission_clock_type')
    )
    op.create_table('stage_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'stage', name='uq_submission_stage')
    )
    op.create_table('stage_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('decision_type', sa.Enum('AUTO_ADVANCE', 'APPROVE_ANYWAY', 'REJECT', name='decision_type'), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('checklist_response_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('external_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_response_id'], ['checklist_responses.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Database-level guarantees the architecture doc requires — not just
    # API-level checks, since those can be bypassed by any future direct-DB
    # write path.
    op.execute(
        "ALTER TABLE stage_decisions ADD CONSTRAINT ck_comment_required_unless_auto_advance "
        "CHECK (decision_type = 'AUTO_ADVANCE' OR comment IS NOT NULL)"
    )
    op.execute(
        "ALTER TABLE stage_decisions ADD CONSTRAINT ck_external_message_required_on_reject "
        "CHECK (decision_type != 'REJECT' OR external_message IS NOT NULL)"
    )
    op.execute("REVOKE UPDATE, DELETE ON audit_events FROM bidso_labs_db_user")


def downgrade() -> None:
    op.execute("GRANT UPDATE, DELETE ON audit_events TO bidso_labs_db_user")
    op.execute("ALTER TABLE stage_decisions DROP CONSTRAINT ck_external_message_required_on_reject")
    op.execute("ALTER TABLE stage_decisions DROP CONSTRAINT ck_comment_required_unless_auto_advance")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_decisions')
    op.drop_table('submission_detail')
    op.drop_table('stage_attachments')
    op.drop_table('sla_clocks')
    op.drop_table('declined_ip_register')
    op.drop_table('deal_shape_decisions')
    op.drop_table('checklist_responses')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_reference_number'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('terms_versions')
    op.drop_table('sequence_counters')
    op.drop_table('checklist_templates')
    # ### end Alembic commands ###
